# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/rajpo/Desktop/This Semister/CMPEN 331/Lab 5/CPU/CPU.cache/wt} [current_project]
set_property parent.project_path {C:/Users/rajpo/Desktop/This Semister/CMPEN 331/Lab 5/CPU/CPU.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/rajpo/Desktop/This Semister/CMPEN 331/Lab 5/CPU/CPU.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/rajpo/Desktop/This Semister/CMPEN 331/Lab 5/Sources/2_1_Mux.v}
  {C:/Users/rajpo/Desktop/This Semister/CMPEN 331/Lab 5/Sources/ALU.v}
  {C:/Users/rajpo/Desktop/This Semister/CMPEN 331/Lab 5/Sources/ALU_Mux.v}
  {C:/Users/rajpo/Desktop/This Semister/CMPEN 331/Lab 5/Sources/Adder.v}
  {C:/Users/rajpo/Desktop/This Semister/CMPEN 331/Lab 5/Sources/ControlUnit.v}
  {C:/Users/rajpo/Desktop/This Semister/CMPEN 331/Lab 5/Sources/Data_Memory.v}
  {C:/Users/rajpo/Desktop/This Semister/CMPEN 331/Lab 5/Sources/InstructionMemory.v}
  {C:/Users/rajpo/Desktop/This Semister/CMPEN 331/Lab 5/Sources/Mem_Mux.v}
  {C:/Users/rajpo/Desktop/This Semister/CMPEN 331/Lab 5/Sources/RegisterFile.v}
  {C:/Users/rajpo/Desktop/This Semister/CMPEN 331/Lab 5/Sources/SignExtender.v}
  {C:/Users/rajpo/Desktop/This Semister/CMPEN 331/Lab 5/Sources/CPU.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top CPU -part xc7z010clg400-3


write_checkpoint -force -noxdef CPU.dcp

catch { report_utilization -file CPU_utilization_synth.rpt -pb CPU_utilization_synth.pb }
